matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
           RELEASE_PYTHONS="/opt/python/cp27-cp27mu/bin/python,/opt/python/cp35-cp35m/bin/python,/opt/python/cp36-cp36m/bin/python,/opt/python/cp37-cp37m/bin/python,/opt/python/cp38-cp38/bin/python"

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -e RELEASE_PYTHONS=$RELEASE_PYTHONS -v `pwd`:/io $DOCKER_IMAGE bash /io/dev/build-wheels.sh
  - ls dist/* wheelhouse/*
